theme: jekyll-theme-cayman
title: Welcome to my github page, about...using raspberry pi @ home!
description: I will be describing how to use and configure raspberry pi in some usefull and fun home project.
