theme: jekyll-theme-cayman
title: Welcome to the my personal homepage, about...using raspberry pi @ home!
description: I will be describing how to use and configure raspberry pi in some usefull and fun home project.
